//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cronograma()
        {
            this.Tarea = new HashSet<Tarea>();
        }
    
        public System.Guid Id { get; set; }
        public int Guardia_guardia_id { get; set; }
        public int Empleado_empleado_id { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public string observaciones { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Guardia Guardia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
