//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Tarea = new HashSet<Tarea>();
        }
    
        public int equipo_id { get; set; }
        public string nombre { get; set; }
        public string estadoActual { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string numeroSerie { get; set; }
        public System.DateTime inicioOperacion { get; set; }
        public Nullable<System.DateTime> finOperacion { get; set; }
        public bool esCritico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
