//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Recurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recurso()
        {
            this.Recurso_DetalleTarea = new HashSet<Recurso_DetalleTarea>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Key]
        public int recurso_id { get; set; }

        [Required(ErrorMessage = "El Stock es requerido")]
        [Display(Name = "Stock")]
        public double cantidadStock { get; set; }

        [Required(ErrorMessage = "El nombre es requerido")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "El Nombre debe tener una longitud menor de 50 caracteres")]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "La marca es requerido")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "La marca debe tener una longitud menor de 20 caracteres")]
        [Display(Name = "Marca")]
        public string marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recurso_DetalleTarea> Recurso_DetalleTarea { get; set; }
    }
}
