//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso_DetalleTarea
    {
        public int detalleTarea_id { get; set; }
        public int recurso_id { get; set; }
        public Nullable<double> cantidadUsada { get; set; }
    
        public virtual Detalle_Tarea Detalle_Tarea { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
